name: flutter_ui_designs
description: Flutter UI Designs

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.2+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.4.2
  provider: ^3.1.0+1
  flutter_bloc: ^0.5.4
  http: ^0.12.0
  font_awesome_flutter: ^8.2.0
  simple_gesture_detector: ^0.1.3
  table_calendar: ^2.1.0
  intl: ^0.16.0
  cached_network_image: ^0.8.0
  flutter_sparkline: ^0.1.0
  flutter_staggered_grid_view: ^0.3.0
  fluttertoast: ^3.1.3
  loader_search_bar: ^1.0.3+3

  reorderables: ^0.2.12
  bsev: ^0.8.0
  share: ^0.6.0+1
  dio: 1.0.0
  english_words: 3.1.5
  badges: ^1.1.0
  sliding_up_panel: ^0.3.6
  auto_size_text: ^1.1.2
  bubble_bottom_bar: ^1.2.0
  package_info: ^0.4.0+10
  image_picker: ^0.6.1+10

  multi_charts: ^0.1.0

  timezone: ^0.5.2
  sqflite:
  path:
  shared_preferences: ^0.5.4+3
  kiwi: ^0.2.0
  moor_flutter: ^2.0.0
  flutter_vector_icons: ^0.2.1
  random_color: ^1.0.3
  flutter_material_color_picker: ^1.0.5
  flutter_colorpicker: ^0.2.6
  flushbar: ^1.9.1
  direct_select: ^1.0.0
  flutter_form_builder: ^3.6.0
  convert: ^2.1.1
  charts_flutter: ^0.8.1
  firebase_auth: ^0.14.0+8
  cloud_firestore: ^0.12.10
  firebase_storage: ^3.0.8




dev_dependencies:
  pedantic: ^1.4.0
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/atro/atro_login_background.png
    - assets/atro/facebook.png
    - assets/atro/ui-logo.png
    - assets/atro/logo.png
    - assets/atro/Football.png
    - assets/atro/football1.png
    - assets/atro/B4.jpg
    - assets/atro/B6.jpg
    - assets/atro/B3.jpg
    - assets/atro/B2.jpg
    - assets/atro/B1.jpg
    - assets/atro/facebook-button.png
    - assets/atro/google.png
    - assets/Ton.jpg
    - assets/Ohh.jpg
    - assets/Team.jpg
    - assets/Soc.jpg
    - assets/Player.png
    - assets/Player1.png
    - assets/Team.png
    - assets/default.png
    - assets/Team1.png
    - assets/AllTeam.png
    - assets/AllTeam1.png
    - assets/Stadium.png
    - assets/Stadium1.png
    - assets/Stats.png
    - assets/Stats1.png
    - assets/Market.png
    - assets/Market1.png
    - assets/Shirt.png
    - assets/T.jpg
    - assets/Club.jpg
    - assets/Flag.jpg



  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:

    - family: Montserrat
      fonts:
        - asset: assets/atro/fonts/Montserrat-Regular.ttf
        - asset: assets/atro/fonts/Montserrat-Bold.ttf


    - family: CupertinoIcons
      fonts:
         - asset: assets/CupertinoIcons.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
assets/teamicon1:
  png: